### ISSUE TITLE
大神您好，可以简单说下怎么使用吗？

### ISSUE THREAD

**Issue by hellowqw** [QueryStyle/GFW#1]
想翻墙很久了，可是怎么都学不会，可以教教我吗？或者您给指条明路，哪里可以学习到～非常感谢！

**Comment by QueryStyle** [comment]
@hellowqw 
请看这个项目，里面有使用方式和已经打包好的版本
https://github.com/gwuhaolin/lightsocks
如果想要看实现过程，可以看这个，写得比较详细
https://github.com/gwuhaolin/blog/issues/12
